import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/page-header";
import BottomNav from "@/components/bottom-nav";
import { Toaster } from "@/components/ui/toaster";
import { NextAuthProvider } from "./_app";

export const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head />
            <body
                className={cn(
                    "min-h-screen bg-background font-sans antialiased bg-zinc-400",
                    fontSans.variable
                )}
            >
                <NextAuthProvider>
                    <main className="max-w-xl bg-white mx-auto min-h-screen">
                        <Header />
                        <div className="p-4 pt-4">{children}</div>
                        <BottomNav />
                    </main>
                </NextAuthProvider>
                <Toaster />
            </body>
        </html>
    );
}
